@startuml

left to right direction

node WebServer {
   https - [Apache]
}

node Container {
    http - [Application]
}
package PlatformServices {
    registry -- [ServiceRegistry]
    config -- [ConfigurationService]

}
package BackingServices {
    cache -- [DistributedCache]
    jdbc -- [RelationalDatabase]
    amqp -- [MessageQueueServer]
    smtp -- [MailServer]
    docrest -- [DocumentDatabase]
    logging -- [LoggingStore]
}

Apache --> http: <<load-balancing>>
Application --> jdbc
Application ..> config
Application ..> registry
Application --> docrest
Application --> amqp
Application --> smtp
Application ..> cache
Application ..> logging
Apache ..> logging

@enduml